#!/usr/bin/env bash
# check-drift.sh — the prose and the code must agree with the surface table.
#
# The CLI's agent-facing contract is prose: README.md, `uku --help`, and the
# skill `uku setup agents` installs. Prose drifts in TWO directions and both
# cost us:
#
#   1. the docs PROMISE FICTION — a command or a flag that does not exist. An
#      agent follows it, gets exit 1, and distrusts the tool. (We shipped a
#      launch like that once; this file exists so it cannot happen twice.)
#   2. the docs are SILENT about surface that does exist. Nobody can use what
#      nobody can find — surface we paid for and cannot sell.
#
# Four checks, and check 3 is the one that keeps the other three honest: a
# hand-written table that quietly falls behind the code would make every other
# check pass while meaning nothing. Static parsing of bash is imperfect, so
# check 3 does not only parse — it EXECUTES: every command in the table is
# handed to the real dispatcher and must be recognised.
#
#   1  README.md names nothing that does not exist
#   2  the embedded skill names nothing that does not exist
#   3  the table names everything the code dispatches (parsed AND executed)
#   4  the table's own surface is discoverable in `uku --help`
#
# bash 3.2 compatible.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UKU="$ROOT/bin/uku"
SURFACE="$ROOT/.surface"
INTERNAL="$ROOT/.surface-internal"
BASELINE="$ROOT/.surface-drift-baseline"

[ -f "$SURFACE" ] || { printf 'no .surface — run scripts/check-surface.sh --update first\n' >&2; exit 2; }

TMP="$(mktemp -d "${TMPDIR:-/tmp}/uku-drift-XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
FAIL=0

# ── inputs ───────────────────────────────────────────────────────────
# The skill is not a file in the repo — it is generated by `uku setup agents`.
# Generate it the way a user gets it, into a throwaway HOME, and check THAT.
mkdir -p "$TMP/home"
HOME="$TMP/home" UKU_SETUP_AGENT=claude UKU_NO_AUTO_UPDATE=1 \
  "$UKU" setup agents >/dev/null 2>&1 || true
SKILL="$TMP/home/.claude/skills/uku/SKILL.md"
[ -f "$SKILL" ] || { printf 'could not generate the skill via `uku setup agents`\n' >&2; exit 2; }

NO_COLOR=1 UKU_NO_AUTO_UPDATE=1 "$UKU" --help > "$TMP/help" 2>/dev/null || true

# tolerated, pre-existing mismatches — one per line, `# ` comment says why
: > "$TMP/baseline"
[ -f "$BASELINE" ] && grep -v '^[[:space:]]*#' "$BASELINE" | grep -v '^[[:space:]]*$' > "$TMP/baseline" || true
: > "$TMP/internal"
[ -f "$INTERNAL" ] && grep -v '^[[:space:]]*#' "$INTERNAL" | grep -v '^[[:space:]]*$' \
  | sed 's/[[:space:]]*#.*$//' | grep -v '^[[:space:]]*$' > "$TMP/internal" || true

_excused() { grep -qxF "$1" "$TMP/baseline" 2>/dev/null; }
_internal() { grep -qxF "$1" "$TMP/internal" 2>/dev/null; }
_fact()    { grep -qxF "$1" "$SURFACE"; }

_report() { # SLUG MESSAGE  → record a finding unless baselined
  if _excused "$1"; then return 0; fi
  printf '    ✗ %s\n' "$2" >&2
  FAIL=$((FAIL + 1))
  return 0
}

# ── 1 & 2: the docs must not promise fiction ─────────────────────────
# Every `uku <command> [<subcommand>]` and every `--flag` a document names has
# to be a fact in .surface. Uppercase words (`uku api GET …`) and placeholders
# (`uku <res> get <id>`) are values, not surface, and are skipped.
check_doc() { # LABEL FILE
  local label="$1" file="$2" line cmd sub flag
  printf '  %s\n' "$label"

  grep -oE '(^|[^A-Za-z0-9_/-])uku [a-z][a-z0-9-]*( [a-z][a-z0-9-]*)?' "$file" \
    | sed 's/^[^u]*uku /uku /' | LC_ALL=C sort -u > "$TMP/mentions" || true
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    set -- $line   # uku CMD [SUB]
    cmd="${2:-}"; sub="${3:-}"
    [ -n "$cmd" ] || continue
    if ! _fact "cmd $cmd" && ! grep -qE "^cmdalias [a-z-]+ $cmd\$" "$SURFACE"; then
      _report "doc-cmd $cmd" "$label names \`uku $cmd\` — no such command. Fix: correct the doc, or add the command to the table in bin/uku."
      continue
    fi
    [ -n "$sub" ] || continue
    # only commands that HAVE subcommands can have a wrong one; for the others
    # (uku api GET …, uku help batch) the second word is a value.
    grep -qE "^sub $cmd " "$SURFACE" || continue
    if ! _fact "sub $cmd $sub" && ! _fact "subalias $cmd $sub"; then
      _report "doc-sub $cmd $sub" "$label names \`uku $cmd $sub\` — $cmd has no \`$sub\` subcommand. Fix: correct the doc, or declare the subcommand in the table."
    fi
  done < "$TMP/mentions"

  grep -oE '(^|[^-[:alnum:]])--[a-z][a-z0-9-]*' "$file" | sed 's/^.*--/--/' \
    | LC_ALL=C sort -u > "$TMP/docflags" || true
  while IFS= read -r flag; do
    [ -n "$flag" ] || continue
    if ! _fact "gflag $flag" && ! grep -qE "^flag [a-z-]+ $flag\$" "$SURFACE"; then
      _report "doc-flag $flag" "$label names \`$flag\` — no command accepts it. Fix: correct the doc, or declare the flag in the table."
    fi
  done < "$TMP/docflags"
  return 0
}

printf '\ndrift: docs → surface\n'
check_doc "README.md" "$ROOT/README.md"
check_doc "the embedded skill (uku setup agents)" "$SKILL"

# ── 3: the table must not lie by omission ────────────────────────────
printf '\ndrift: code → surface\n'

# 3a — every cmd_* function in the source is a command in the table.
printf '  cmd_* functions in bin/uku\n'
grep -oE '^cmd_[a-z_]+\(\)' "$UKU" | sed 's/()$//; s/^cmd_//' | LC_ALL=C sort -u > "$TMP/fns"
while IFS= read -r line; do
  [ -n "$line" ] || continue
  _fact "cmd $line" || \
    _report "code-fn $line" "bin/uku defines cmd_$line() but the table has no \`$line\` command. Fix: add the row (or, if it is not reachable, delete the function)."
done < "$TMP/fns"

# 3b — every label the dispatcher answers to is in the table.
printf '  case labels in the dispatcher\n'
awk '/case "\$cmd" in/,/^esac/' "$UKU" \
  | grep -oE '^[[:space:]]+[a-z_|-]+\)' | tr -d ' )' | tr '|' '\n' \
  | grep -v '^__firstrun__$' | grep -v '^$' | LC_ALL=C sort -u > "$TMP/labels"
while IFS= read -r line; do
  [ -n "$line" ] || continue
  if ! _fact "cmd $line" && ! grep -qE "^cmdalias [a-z-]+ $line\$" "$SURFACE"; then
    _report "code-label $line" "the dispatcher answers to \`uku $line\` but the table does not declare it. Fix: add it as a command or a cmd-alias in bin/uku."
  fi
done < "$TMP/labels"

# 3c — parsing bash is imperfect, so PROVE the other direction by executing:
# hand each declared command to the real dispatcher and require that it is
# recognised. Hermetic: a throwaway HOME/config, a base that cannot resolve to
# anything real, no auto-update, no agent files written.
printf '  every declared command is recognised by the dispatcher (executed)\n'
probe() { # NAME
  HOME="$TMP/home" \
  UKU_CONFIG_HOME="$TMP/cfg" \
  UKU_BASE_URL="http://127.0.0.1:9" \
  UKU_UPDATE_URL="http://127.0.0.1:9/VERSION" \
  UKU_INSTALL_URL="http://127.0.0.1:9/never" \
  UKU_SETUP_AGENT=none \
  UKU_NO_AUTO_UPDATE=1 NO_COLOR=1 \
    "$UKU" "$1" __surface_probe__ </dev/null >/dev/null 2>"$TMP/probe.err" || true
  grep -q 'unknown command' "$TMP/probe.err" && return 1
  return 0
}
{ grep '^cmd ' "$SURFACE" | cut -d' ' -f2; grep '^cmdalias ' "$SURFACE" | cut -d' ' -f3; } \
  | LC_ALL=C sort -u > "$TMP/declared"
while IFS= read -r line; do
  [ -n "$line" ] || continue
  probe "$line" || \
    _report "probe $line" "the table declares \`uku $line\` but the dispatcher rejects it as an unknown command. Fix: remove the row, or add the case label in bin/uku."
done < "$TMP/declared"

# ── 4: nothing undiscoverable by accident ────────────────────────────
# Every command must be findable in `uku --help`, and so must every piece of
# surface the table marks `!` (a `doc` fact). Anything deliberately hidden is
# listed, with a reason, in .surface-internal.
printf '\ndrift: surface → uku help\n'
printf '  every command appears in uku --help\n'
while IFS= read -r line; do
  [ -n "$line" ] || continue
  if grep -qF "uku $line" "$TMP/help"; then continue; fi
  _internal "cmd $line" && continue
  _report "help-cmd $line" "\`uku $line\` exists but \`uku --help\` never mentions it — nobody can discover it. Fix: document it in usage() in bin/uku, or add \`cmd $line\` to .surface-internal with a reason."
done < <(grep '^cmd ' "$SURFACE" | cut -d' ' -f2)

printf '  every global flag appears in uku --help\n'
while IFS= read -r line; do
  [ -n "$line" ] || continue
  grep -qF -- "$line" "$TMP/help" && continue
  _internal "gflag $line" && continue
  _report "help-gflag $line" "\`$line\` works on every command but \`uku --help\` never shows it. Fix: list it under GLOBAL FLAGS in bin/uku, or add \`gflag $line\` to .surface-internal with a reason."
done < <(grep '^gflag ' "$SURFACE" | cut -d' ' -f2)

printf '  every !must-document fact appears in uku --help\n'
while IFS= read -r line; do
  [ -n "$line" ] || continue
  set -- $line   # doc CMD TOKEN
  case "$3" in
    --*) grep -qF -- "$3" "$TMP/help" && continue ;;
    *)   grep -qF -- "uku $2 $3" "$TMP/help" && continue ;;
  esac
  _internal "doc $2 $3" && continue
  _report "help-doc $2 $3" "the table marks \`$2 $3\` as must-document, but \`uku --help\` does not show it. Fix: add it to usage() in bin/uku, drop the \`!\` from the table, or excuse it in .surface-internal."
done < <(grep '^doc ' "$SURFACE")

# ── verdict ──────────────────────────────────────────────────────────
n_base="$(wc -l < "$TMP/baseline" | tr -d ' ')"
printf '\n'
if [ "$FAIL" -gt 0 ]; then
  printf 'drift: %d problem(s). Nothing here is cosmetic — each one is prose an\n' "$FAIL" >&2
  printf '       agent will act on, or surface an agent will never find.\n' >&2
  exit 1
fi
printf 'drift: clean'
[ "$n_base" = "0" ] || printf ' (%s tolerated in .surface-drift-baseline)' "$n_base"
printf '.\n'
exit 0
